import type { AppState, Media, SocialPost } from "./types";

const image = (id: string, width: number, height: number) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&h=${height}&q=86`;

const episodes = (season: number, titles: string[]) =>
  titles.map((title, index) => ({
    id: `s${season}e${index + 1}`,
    number: index + 1,
    title,
    runtime: 47 + ((index * 3) % 12),
    synopsis:
      [
        "A quiet discovery shifts the balance inside the team.",
        "Old loyalties are tested as a new path begins to emerge.",
        "The consequences of an impossible choice finally surface.",
      ][index % 3] ?? "The story continues.",
  }));

export const media: Media[] = [
  {
    id: "severance",
    title: "Severance",
    year: 2022,
    format: "series",
    poster: image("photo-1485846234645-a62644f84728", 720, 1080),
    backdrop: image("photo-1497366811353-6870744d04b2", 1800, 1050),
    accent: "#d45b43",
    runtime: 52,
    seasons: [
      {
        number: 1,
        year: 2022,
        episodes: episodes(1, [
          "Good News About Hell",
          "Half Loop",
          "In Perpetuity",
          "The You You Are",
          "The Grim Barbarity of Optics and Design",
          "Hide and Seek",
          "Defiant Jazz",
          "What's for Dinner?",
          "The We We Are",
        ]),
      },
      {
        number: 2,
        year: 2025,
        episodes: episodes(2, [
          "Hello, Ms. Cobel",
          "Goodbye, Mrs. Selvig",
          "Who Is Alive?",
          "Woe's Hollow",
          "Trojan's Horse",
          "Attila",
          "Chikhai Bardo",
          "Sweet Vitriol",
          "The After Hours",
          "Cold Harbor",
        ]),
      },
    ],
    genres: ["Science fiction", "Mystery", "Drama"],
    moods: ["Tense", "Strange", "Thoughtful"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 8,
    synopsis:
      "Mark leads a team whose memories have been surgically divided between their work and personal lives. A mysterious colleague forces him to confront the truth of their jobs.",
    creators: ["Dan Erickson", "Ben Stiller"],
    cast: ["Adam Scott", "Britt Lower", "Patricia Arquette"],
    services: ["Apple TV+"],
    country: "United States",
    language: "English",
    availabilityNote: "New episode Friday",
  },
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    year: 2024,
    format: "movie",
    poster: image("photo-1500534314209-a25ddb2bd4297", 720, 1080),
    backdrop: image("photo-1547234935-80c7145ec969", 1800, 1050),
    accent: "#d7985d",
    runtime: 166,
    genres: ["Science fiction", "Adventure", "Drama"],
    moods: ["Epic", "Intense", "Transportive"],
    pace: "balanced",
    intensity: "demanding",
    adventurous: 6,
    synopsis:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    creators: ["Denis Villeneuve"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    services: ["Max"],
    country: "United States",
    language: "English",
  },
  {
    id: "past-lives",
    title: "Past Lives",
    year: 2023,
    format: "movie",
    poster: image("photo-1499343245400-cddc78a01317", 720, 1080),
    backdrop: image("photo-1522083165195-3424ed129620", 1800, 1050),
    accent: "#8eaab8",
    runtime: 106,
    genres: ["Romance", "Drama"],
    moods: ["Tender", "Reflective", "Bittersweet"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 4,
    synopsis:
      "Two deeply connected childhood friends are reunited in New York for one fateful week, confronting destiny, love, and the choices that make a life.",
    creators: ["Celine Song"],
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    services: ["MUBI"],
    country: "United States",
    language: "English / Korean",
  },
  {
    id: "dark",
    title: "Dark",
    year: 2017,
    format: "series",
    poster: image("photo-1500673922987-e212871fec22", 720, 1080),
    backdrop: image("photo-1511497584788-876760111969", 1800, 1050),
    accent: "#728779",
    runtime: 56,
    seasons: [
      {
        number: 1,
        year: 2017,
        episodes: episodes(1, [
          "Secrets",
          "Lies",
          "Past and Present",
          "Double Lives",
          "Truths",
          "Sic Mundus Creatus Est",
          "Crossroads",
          "As You Sow, So You Shall Reap",
          "Everything Is Now",
          "Alpha and Omega",
        ]),
      },
      {
        number: 2,
        year: 2019,
        episodes: episodes(2, [
          "Beginnings and Endings",
          "Dark Matter",
          "Ghosts",
          "The Travelers",
          "Lost and Found",
          "An Endless Cycle",
          "The White Devil",
          "Endings and Beginnings",
        ]),
      },
      {
        number: 3,
        year: 2020,
        episodes: episodes(3, [
          "Deja-vu",
          "The Survivors",
          "Adam and Eva",
          "The Origin",
          "Life and Death",
          "Light and Shadow",
          "Between the Time",
          "The Paradise",
        ]),
      },
    ],
    genres: ["Mystery", "Science fiction", "Thriller"],
    moods: ["Dark", "Cerebral", "Atmospheric"],
    pace: "measured",
    intensity: "demanding",
    adventurous: 9,
    synopsis:
      "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery spanning generations.",
    creators: ["Baran bo Odar", "Jantje Friese"],
    cast: ["Louis Hofmann", "Lisa Vicari", "Andreas Pietschmann"],
    services: ["Netflix"],
    country: "Germany",
    language: "German",
  },
  {
    id: "the-bear",
    title: "The Bear",
    year: 2022,
    format: "series",
    poster: image("photo-1556910103-1c02745aae4d", 720, 1080),
    backdrop: image("photo-1516211697506-8360dbcfe9a4", 1800, 1050),
    accent: "#3d86aa",
    runtime: 34,
    seasons: [
      {
        number: 1,
        year: 2022,
        episodes: episodes(1, [
          "System",
          "Hands",
          "Brigade",
          "Dogs",
          "Sheridan",
          "Ceres",
          "Review",
          "Braciole",
        ]),
      },
      {
        number: 2,
        year: 2023,
        episodes: episodes(2, [
          "Beef",
          "Pasta",
          "Sundae",
          "Honeydew",
          "Pop",
          "Fishes",
          "Forks",
          "Bolognese",
          "Omelette",
          "The Bear",
        ]),
      },
      {
        number: 3,
        year: 2024,
        episodes: episodes(3, [
          "Tomorrow",
          "Next",
          "Doors",
          "Violet",
          "Children",
          "Napkins",
          "Legacy",
          "Ice Chips",
          "Apologies",
          "Forever",
        ]),
      },
    ],
    genres: ["Drama", "Comedy"],
    moods: ["Intense", "Human", "Funny"],
    pace: "brisk",
    intensity: "demanding",
    adventurous: 5,
    synopsis:
      "A young fine-dining chef returns home to run his family sandwich shop and finds a crew ready to become something more.",
    creators: ["Christopher Storer"],
    cast: ["Jeremy Allen White", "Ayo Edebiri", "Ebon Moss-Bachrach"],
    services: ["Disney+"],
    country: "United States",
    language: "English",
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    format: "movie",
    poster: image("photo-1446776811953-b23d57bd21aa", 720, 1080),
    backdrop: image("photo-1462331940025-496dfbfc7564", 1800, 1050),
    accent: "#8a969b",
    runtime: 116,
    genres: ["Science fiction", "Drama"],
    moods: ["Thoughtful", "Emotional", "Mysterious"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 7,
    synopsis:
      "A linguist works with the military to communicate with alien lifeforms after mysterious spacecraft appear around the world.",
    creators: ["Denis Villeneuve"],
    cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    services: ["Prime Video"],
    country: "United States",
    language: "English",
  },
  {
    id: "aftersun",
    title: "Aftersun",
    year: 2022,
    format: "movie",
    poster: image("photo-1507525428034-b723cf961d3e", 720, 1080),
    backdrop: image("photo-1510414842594-a61c69b5ae57", 1800, 1050),
    accent: "#69a9bd",
    runtime: 102,
    genres: ["Drama"],
    moods: ["Tender", "Devastating", "Sunlit"],
    pace: "measured",
    intensity: "demanding",
    adventurous: 6,
    synopsis:
      "Twenty years after their last holiday, Sophie reflects on the rare time spent with her loving and idealistic father Calum.",
    creators: ["Charlotte Wells"],
    cast: ["Paul Mescal", "Frankie Corio"],
    services: ["MUBI"],
    country: "United Kingdom",
    language: "English",
  },
  {
    id: "portrait",
    title: "Portrait of a Lady on Fire",
    year: 2019,
    format: "movie",
    poster: image("photo-1534528741775-53994a69daeb", 720, 1080),
    backdrop: image("photo-1518391846015-55a9cc003b25", 1800, 1050),
    accent: "#b75f44",
    runtime: 122,
    genres: ["Romance", "Drama", "History"],
    moods: ["Intimate", "Slow burn", "Romantic"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 7,
    synopsis:
      "A painter is commissioned to create the wedding portrait of a young woman on an isolated French island.",
    creators: ["Céline Sciamma"],
    cast: ["Noémie Merlant", "Adèle Haenel"],
    services: ["MUBI"],
    country: "France",
    language: "French",
  },
  {
    id: "andor",
    title: "Andor",
    year: 2022,
    format: "series",
    poster: image("photo-1518331647614-7a1f04cd34cf", 720, 1080),
    backdrop: image("photo-1516849841032-87cbac4d88f7", 1800, 1050),
    accent: "#b78e5d",
    runtime: 44,
    seasons: [
      {
        number: 1,
        year: 2022,
        episodes: episodes(1, [
          "Kassa",
          "That Would Be Me",
          "Reckoning",
          "Aldhani",
          "The Axe Forgets",
          "The Eye",
          "Announcement",
          "Narkina 5",
          "Nobody’s Listening!",
          "One Way Out",
          "Daughter of Ferrix",
          "Rix Road",
        ]),
      },
    ],
    genres: ["Science fiction", "Thriller", "Drama"],
    moods: ["Political", "Tense", "Grounded"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 5,
    synopsis:
      "The story of a thief whose journey will turn him into a rebel hero during the formative years of the Rebellion.",
    creators: ["Tony Gilroy"],
    cast: ["Diego Luna", "Stellan Skarsgård", "Genevieve O’Reilly"],
    services: ["Disney+"],
    country: "United States",
    language: "English",
  },
  {
    id: "perfect-days",
    title: "Perfect Days",
    year: 2023,
    format: "movie",
    poster: image("photo-1519501025264-65ba15a82390", 720, 1080),
    backdrop: image("photo-1503899036084-c55cdd92da26", 1800, 1050),
    accent: "#9aac79",
    runtime: 124,
    genres: ["Drama"],
    moods: ["Gentle", "Reflective", "Comforting"],
    pace: "measured",
    intensity: "light",
    adventurous: 7,
    synopsis:
      "A cleaner in Tokyo lives a life of quiet routine, music, books, and photographs, finding beauty in the everyday.",
    creators: ["Wim Wenders"],
    cast: ["Kōji Yakusho", "Arisa Nakano"],
    services: ["Hulu"],
    country: "Japan",
    language: "Japanese",
  },
  {
    id: "poor-things",
    title: "Poor Things",
    year: 2023,
    format: "movie",
    poster: image("photo-1518709268805-4e9042af9f23", 720, 1080),
    backdrop: image("photo-1500530855697-b586d89ba3ee", 1800, 1050),
    accent: "#c65c79",
    runtime: 141,
    genres: ["Fantasy", "Comedy", "Drama"],
    moods: ["Playful", "Strange", "Bold"],
    pace: "balanced",
    intensity: "balanced",
    adventurous: 10,
    synopsis:
      "A young woman brought back to life runs off on a whirlwind adventure across continents, hungry for experience and equality.",
    creators: ["Yorgos Lanthimos"],
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe"],
    services: ["Disney+"],
    country: "Ireland",
    language: "English",
  },
  {
    id: "decision-to-leave",
    title: "Decision to Leave",
    year: 2022,
    format: "movie",
    poster: image("photo-1534274988757-a28bf1a57c17", 720, 1080),
    backdrop: image("photo-1500530855697-b586d89ba3ee", 1800, 1050),
    accent: "#7896a1",
    runtime: 138,
    genres: ["Mystery", "Romance", "Drama"],
    moods: ["Romantic", "Mysterious", "Elegant"],
    pace: "measured",
    intensity: "balanced",
    adventurous: 8,
    synopsis:
      "A detective investigating a death in the mountains becomes entangled with the victim’s enigmatic widow.",
    creators: ["Park Chan-wook"],
    cast: ["Tang Wei", "Park Hae-il"],
    services: ["MUBI"],
    country: "South Korea",
    language: "Korean / Mandarin",
  },
  {
    id: "columbus",
    title: "Columbus",
    year: 2017,
    format: "movie",
    poster: image("photo-1487958449943-2429e8be8625", 720, 1080),
    backdrop: image("photo-1497366754035-f200968a6e72", 1800, 1050),
    accent: "#91a89b",
    runtime: 104,
    genres: ["Drama", "Romance"],
    moods: ["Gentle", "Reflective", "Architectural"],
    pace: "measured",
    intensity: "light",
    adventurous: 7,
    synopsis:
      "A Korean-born man and a young architecture enthusiast find one another while both feel suspended by family obligations.",
    creators: ["Kogonada"],
    cast: ["John Cho", "Haley Lu Richardson", "Parker Posey"],
    services: ["Kanopy"],
    country: "United States",
    language: "English / Korean",
  },
  {
    id: "memories-of-murder",
    title: "Memories of Murder",
    year: 2003,
    format: "movie",
    poster: image("photo-1519500528352-2d1460418d41", 720, 1080),
    backdrop: image("photo-1473445361085-b9a07f55608b", 1800, 1050),
    accent: "#8f8a56",
    runtime: 131,
    genres: ["Crime", "Mystery", "Drama"],
    moods: ["Dark", "Unsettling", "Absorbing"],
    pace: "measured",
    intensity: "demanding",
    adventurous: 8,
    synopsis:
      "Two detectives in a small Korean province struggle with a string of brutal, unsolved murders and their own limitations.",
    creators: ["Bong Joon Ho"],
    cast: ["Song Kang-ho", "Kim Sang-kyung"],
    services: ["Prime Video"],
    country: "South Korea",
    language: "Korean",
  },
];

const savedAt = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86400000).toISOString();

export const initialState: AppState = {
  version: 1,
  userMedia: {
    severance: {
      mediaId: "severance",
      status: "watching",
      progress: { season: 2, episode: 3 },
      watchedDates: [savedAt(13), savedAt(8), savedAt(2)],
      savedAt: savedAt(120),
    },
    "dune-part-two": {
      mediaId: "dune-part-two",
      status: "completed",
      watchedDates: [savedAt(38)],
      savedAt: savedAt(180),
      verdict: {
        kind: "all-timer",
        normalized: 0.96,
        qualities: ["Visuals", "Soundtrack", "Atmosphere"],
        tags: ["Worth the hype"],
        recordedAt: savedAt(38),
        rank: 2,
      },
    },
    "past-lives": {
      mediaId: "past-lives",
      status: "up-next",
      watchedDates: [],
      savedAt: savedAt(96),
      intent: {
        reason: "For a quiet evening",
        recommendedBy: "Maya",
        priority: "high",
        mood: "Reflective",
      },
    },
    dark: {
      mediaId: "dark",
      status: "completed",
      progress: { season: 3, episode: 8 },
      watchedDates: [savedAt(500)],
      savedAt: savedAt(700),
      verdict: {
        kind: "loved",
        normalized: 0.89,
        qualities: ["Story", "Atmosphere", "Originality"],
        tags: ["Slow burn", "Strong ending"],
        recordedAt: savedAt(500),
        rank: 5,
      },
    },
    "the-bear": {
      mediaId: "the-bear",
      status: "paused",
      progress: { season: 3, episode: 4 },
      watchedDates: [savedAt(72)],
      savedAt: savedAt(400),
      verdict: {
        kind: "loved",
        normalized: 0.84,
        qualities: ["Performances", "Characters"],
        tags: ["Great chemistry"],
        recordedAt: savedAt(72),
      },
    },
    arrival: {
      mediaId: "arrival",
      status: "completed",
      watchedDates: [savedAt(310), savedAt(44)],
      savedAt: savedAt(900),
      verdict: {
        kind: "all-timer",
        normalized: 0.98,
        qualities: ["Emotion", "Ending", "Soundtrack"],
        tags: ["Devastating", "Strong ending"],
        recordedAt: savedAt(44),
        rank: 1,
      },
    },
    aftersun: {
      mediaId: "aftersun",
      status: "planned",
      watchedDates: [],
      savedAt: savedAt(190),
      intent: {
        reason: "Loved Past Lives",
        priority: "medium",
        mood: "Reflective",
      },
    },
    portrait: {
      mediaId: "portrait",
      status: "planned",
      watchedDates: [],
      savedAt: savedAt(260),
      intent: { recommendedBy: "Sara", withWhom: "Sara", priority: "medium" },
    },
    andor: {
      mediaId: "andor",
      status: "up-next",
      progress: { season: 1, episode: 2 },
      watchedDates: [savedAt(80)],
      savedAt: savedAt(300),
      intent: { reason: "Continue before the new season", priority: "high" },
    },
    "perfect-days": {
      mediaId: "perfect-days",
      status: "planned",
      watchedDates: [],
      savedAt: savedAt(12),
      intent: { mood: "Comforting", priority: "high" },
    },
    "poor-things": {
      mediaId: "poor-things",
      status: "completed",
      watchedDates: [savedAt(61)],
      savedAt: savedAt(240),
      verdict: {
        kind: "liked",
        normalized: 0.74,
        qualities: ["Visuals", "Performances", "Originality"],
        tags: ["Great concept"],
        recordedAt: savedAt(61),
        rank: 12,
      },
    },
    "memories-of-murder": {
      mediaId: "memories-of-murder",
      status: "archived",
      watchedDates: [],
      savedAt: savedAt(420),
      intent: { reason: "Bong Joon Ho deep dive", priority: "low" },
    },
  },
  events: [
    {
      id: "e1",
      mediaId: "severance",
      type: "episode",
      season: 2,
      episode: 3,
      watchedAt: savedAt(2),
    },
    { id: "e2", mediaId: "arrival", type: "rewatch", watchedAt: savedAt(44) },
    { id: "e3", mediaId: "poor-things", type: "movie", watchedAt: savedAt(61) },
    {
      id: "e4",
      mediaId: "the-bear",
      type: "episode",
      season: 3,
      episode: 4,
      watchedAt: savedAt(72),
    },
  ],
  shelves: [
    {
      id: "weekend",
      title: "Weekend films",
      description: "Unhurried films worth giving the whole evening to.",
      mediaIds: ["past-lives", "aftersun", "portrait"],
      featuredId: "past-lives",
      visibility: "private",
      atmosphere: "#7f695f",
    },
    {
      id: "strange",
      title: "Beautifully strange",
      description: "Bold worlds, odd rules, complete commitment.",
      mediaIds: ["poor-things", "severance", "dark"],
      featuredId: "poor-things",
      visibility: "public",
      atmosphere: "#76525f",
    },
    {
      id: "friends",
      title: "Watch with friends",
      description: "A short, intentional queue for shared nights.",
      mediaIds: ["andor", "dune-part-two", "memories-of-murder"],
      featuredId: "andor",
      visibility: "collaborative",
      atmosphere: "#5e6559",
    },
  ],
  queue: ["past-lives", "perfect-days", "andor", "aftersun"],
  filters: {
    maxRuntime: 150,
    format: "any",
    mood: "Any mood",
    services: ["MUBI", "Apple TV+", "Disney+", "Prime Video"],
    company: "alone",
    familiarity: "familiar",
    intensity: "balanced",
  },
  room: {
    id: "room-1",
    name: "Friday film",
    host: "You",
    participants: ["You", "Sara", "Maya"],
    constraints: {
      format: "movie",
      maxRuntime: 150,
      mood: "Atmospheric",
      services: ["MUBI", "Prime Video"],
    },
    candidates: [
      {
        mediaId: "past-lives",
        reason: "On two watchlists · tender and under two hours",
        votes: { Sara: "yes", Maya: "yes" },
      },
      {
        mediaId: "perfect-days",
        reason: "Nobody has seen it · matches the quieter mood",
        votes: { Sara: "maybe", Maya: "yes" },
      },
      {
        mediaId: "memories-of-murder",
        reason: "Your shared taste leans toward patient mysteries",
        votes: { Sara: "yes", Maya: "maybe" },
      },
    ],
  },
};

export const socialPosts: SocialPost[] = [
  {
    id: "p1",
    author: "Sara",
    avatar: "SA",
    text: "The restraint in this episode makes the final scene land even harder.",
    kind: "reaction",
    scope: { mediaId: "severance", level: "episode", season: 2, episode: 3 },
    createdAt: savedAt(1),
  },
  {
    id: "p2",
    author: "Maya",
    avatar: "MY",
    text: "I have a theory about what Cold Harbor really means.",
    kind: "theory",
    scope: { mediaId: "severance", level: "episode", season: 2, episode: 8 },
    createdAt: savedAt(1),
  },
  {
    id: "p3",
    author: "Jonas",
    avatar: "JO",
    text: "One of the rare sequels that deepens every idea from the first film.",
    kind: "review",
    scope: { mediaId: "dune-part-two", level: "title" },
    createdAt: savedAt(9),
  },
];

export const getMedia = (id: string) => media.find((item) => item.id === id);
